Repository marblejs/marble, pull requests merged in 2018-06, with the labels that each got.

#44 fix(core): strict function types for `http` server types
  example/package-lock.json
  example/package.json
  example/src/index.ts
  package-lock.json
  package.json
  packages/core/src/http.interface.ts
  packages/core/src/http.listener.ts
  packages/core/src/operators/matchPath/matchPath.operator.ts
  packages/core/src/operators/matchPath/urlParams.factory.ts
  packages/core/src/response/response.handler.ts
Labels: bug, enhancement, example

#45 fix(core): more correct solution for strictFunctionTypes flag
  packages/core/src/http.listener.ts
Labels: enhancement

#42 style(core): function composition for `matcherFactory` and `queryParamsFactory`
  packages/core/src/operators/matchPath/matcher.factory.ts
  packages/core/src/operators/matchPath/queryParams.factory.ts
  packages/core/src/util/compose.util.ts
Labels: enhancement

#48 fix(logger): display proper response time
  packages/middleware-logger/src/index.ts
  packages/middleware-logger/src/time.factory.spec.ts
  packages/middleware-logger/src/time.factory.ts
Labels: bug

#47 feat(core): use middlewares with `combinedRoutes`
  packages/core/src/effects/effects.combiner.spec.ts
  packages/core/src/effects/effects.combiner.ts
  packages/core/src/effects/effects.helpers.spec.ts
  packages/core/src/effects/effects.helpers.ts
  packages/core/src/effects/effects.interface.ts
Labels: enhancement

#49 feat(core): export compose utility function from `core` package
  packages/core/src/index.spec.ts
  packages/core/src/index.ts
  packages/middleware-logger/src/index.ts
  packages/middleware-logger/src/time.factory.spec.ts
  packages/middleware-logger/src/time.factory.ts
Labels: enhancement

#50 feat(middleware-body): support for x-www-form-urlencoded
  package-lock.json
  packages/core/src/util/contentType.util.ts
  packages/middleware-body/src/indes.spec.ts
  packages/middleware-body/src/index.ts
  packages/middleware-body/src/urlEncoded.serializer.spec.ts
  packages/middleware-body/src/urlEncoded.serializer.ts
Labels: enhancement

#51 perf(core): optimized middlewares composition
  benchmarks/middleware.js
  package.json
  packages/core/src/effects/effects.combiner.ts
  packages/core/src/http.listener.ts
Labels: enhancement
