Repository marblejs/marble, pull requests merged in 2018-05, with the labels that each got.

#6 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: docs

#9 feature - compose middlewares inside Effect pipeline
  packages/core/src/http.listener.spec.ts
  packages/core/src/operators/use.operator.spec.ts
  packages/core/src/operators/use.operator.ts
Labels: enhancement

#8 feature - intercepting url parameters
  packages/core/package-lock.json
  packages/core/src/http.interface.ts
  packages/core/src/http.listener.spec.ts
  packages/core/src/operators/matchPath.operator.spec.ts
  packages/core/src/operators/matchPath.operator.ts
Labels: enhancement

#10 Adding linter, tests and prettier on pre commit hook
  package-lock.json
  package.json
Labels: enhancement

#12 Update README.md
  README.md
Labels: docs

#14 fix couple typos in readme
  README.md
Labels: docs

#20 docs(issues): Update issue templates
  ISSUE_TEMPLATE/feature_request.md
  docs/ISSUE_TEMPLATE/bug_report.md
Labels: docs

#21 docs(README): simple typo
  README.md
Labels: docs

#24 style(core): minor fixes, added new http status
  example/src/fakes/dao.fake.ts
  packages/core/src/http.interface.ts
  packages/core/src/middlewares/bodyParser.middleware.ts
Labels: enhancement

#25 fix(core): Allow parrallel requests to work.
  packages/core/src/http.listener.ts
Labels: bug

#18 imp(example): dao.fake.ts
  example/src/fakes/dao.fake.ts
Labels: example

#23 build(jest): separated tsconfig for test related builds
  jest.config.js
  package.json
  tsconfig.spec.json
Labels: enhancement

#28 tests(core): separated API integration tests
  .prettierignore
  packages/core/src/http.listener.spec.ts
  packages/core/src/operators/matchPath/matchPath.operator.spec.ts
  packages/core/src/operators/matchPath/matchPath.operator.ts
  packages/core/src/specs/api.integration.spec.ts
Labels: enhancement

#13 feat(core): Implementation of default query parameters middleware
  example/src/app.ts
  packages/core/src/http.interface.ts
  packages/core/src/operators/matchPath/matchPath.operator.spec.ts
  packages/core/src/operators/matchPath/matchPath.operator.ts
  packages/core/src/operators/matchPath/queryParams.factory.spec.ts
  packages/core/src/operators/matchPath/queryParams.factory.ts
  packages/core/src/specs/api.integration.spec.ts
Labels: enhancement

#17 feat(middleware): Joi validation middleware
  packages/middleware-joi/LICENSE
  packages/middleware-joi/README.md
  packages/middleware-joi/package-lock.json
  packages/middleware-joi/package.json
  packages/middleware-joi/src/index.ts
  packages/middleware-joi/src/schema.ts
  packages/middleware-joi/test/helpers/api.spec-util.ts
  packages/middleware-joi/test/integration/integration.spec.ts
  packages/middleware-joi/test/unit/body.spec.ts
  packages/middleware-joi/test/unit/header.spec.ts
  packages/middleware-joi/test/unit/params.spec.ts
  packages/middleware-joi/test/unit/query.spec.ts
  packages/middleware-joi/test/unit/schema.spec.ts
  packages/middleware-joi/tsconfig.json
Labels: enhancement

#32 feat(example): example of `use` operator
  .prettierignore
  .prettierrc.json
  example/src/app.ts
  example/src/controllers/api.controller.ts
  example/src/controllers/user.controller.ts
  example/src/fakes/auth.fake.ts
  example/src/fakes/dao.fake.ts
  example/src/middlewares/auth.middleware.ts
Labels: example

#37 feat(core): handle response content types
  docs/assets/index.html
  package-lock.json
  package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/effects/effects.combiner.spec.ts
  packages/core/src/http.listener.ts
  packages/core/src/middlewares/error.middleware.spec.ts
  packages/core/src/operators/matchPath/matchPath.operator.spec.ts
  packages/core/src/operators/matchType/matchType.operator.spec.ts
  packages/core/src/operators/use/use.operator.spec.ts
  packages/core/src/response/response.handler.spec.ts
  packages/core/src/response/response.handler.ts
  packages/core/src/response/responseBody.factory.spec.ts
  packages/core/src/response/responseBody.factory.ts
  packages/core/src/response/responseContentType.factory.spec.ts
  packages/core/src/response/responseContentType.factory.ts
  packages/core/src/response/responseHeaders.factory.spec.ts
  packages/core/src/response/responseHeaders.factory.ts
  packages/core/src/util/contentType.util.ts
  packages/middleware-body/src/indes.spec.ts
  packages/middleware-logger/src/index.spec.ts
  packages/spec/api.integration.spec.ts
  packages/util/fileReader.helper.spec.ts
  packages/util/fileReader.helper.ts
  packages/util/marbles.spec-util.ts
Labels: bug, enhancement

#38 build(prettier): removed prettier
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  packages/core/src/http.listener.ts
  packages/core/src/response/response.handler.ts
  packages/middleware-joi/test/unit/schema.spec.ts
Labels: enhancement

#39 feat(core): ability to pass `data` object inside `HttpError` constructor
  packages/core/src/error/error.middleware.spec.ts
  packages/core/src/error/error.middleware.ts
  packages/core/src/error/error.model.spec.ts
  packages/core/src/error/error.model.ts
  packages/core/src/http.listener.spec.ts
  packages/core/src/http.listener.ts
  packages/core/src/index.ts
  packages/spec/api.integration.spec.ts
Labels: enhancement

#40 fix(core): Effect matching hazard
  packages/core/src/effects/effects.combiner.ts
  packages/core/src/http.interface.ts
  packages/core/src/operators/matchPath/matchPath.operator.spec.ts
  packages/core/src/operators/matchPath/matchPath.operator.ts
  packages/core/src/operators/matchType/matchType.operator.spec.ts
  packages/core/src/operators/matchType/matchType.operator.ts
  packages/spec/routing.integration.spec.ts
Labels: bug, enhancement

#41 feat(core): matchType - match all types using * sign
  example/src/controllers/api.controller.ts
  packages/core/src/operators/matchType/matchType.operator.spec.ts
  packages/core/src/operators/matchType/matchType.operator.ts
Labels: enhancement, example
