Repository marblejs/marble, pull requests merged in 2019-06, with the labels that each got.

#136 feat(serverless): Support for AWS Lambda
  packages/core/src/server/specs/server.factory.spec.ts
  packages/serverless/README.md
  packages/serverless/package.json
  packages/serverless/src/+awsLambda/awsLambda.middleware.ts
  packages/serverless/src/+awsLambda/awsLambda.types.ts
  packages/serverless/src/+awsLambda/awsLambdaHandler.ts
  packages/serverless/src/+awsLambda/awsLambdaProxy.options.ts
  packages/serverless/src/+awsLambda/awsLambdaProxy.ts
  packages/serverless/src/+awsLambda/index.ts
  packages/serverless/src/+awsLambda/spec/__snapshots__/awsLambda.spec.ts.snap
  packages/serverless/src/+awsLambda/spec/awsLambda.middleware.spec.ts
  packages/serverless/src/+awsLambda/spec/awsLambda.postContext.mock.json
  packages/serverless/src/+awsLambda/spec/awsLambda.postEvent.mock.json
  packages/serverless/src/+awsLambda/spec/awsLambda.setup.ts
  packages/serverless/src/+awsLambda/spec/awsLambda.spec.ts
  packages/serverless/src/+awsLambda/spec/awsLambdaProxy.spec.ts
  packages/serverless/src/handler.ts
  packages/serverless/src/index.ts
  packages/serverless/src/serverProxy.helpers.ts
  packages/serverless/src/serverProxy.ts
  packages/serverless/src/spec/serverProxy.helpers.spec.ts
  packages/serverless/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#148 fix(testing/doc-gen): Removed const in favor of enum
  packages/middleware-io/src/io.json-schema.ts
  packages/middleware-io/src/specs/io.json-schema.spec.ts
  packages/middleware-io/src/specs/io.request.middleware.spec.ts
Labels: scope: testing

#147 fix(core): request url parse error
  packages/@integration/test/integration.spec.ts
  packages/core/src/response/response.handler.ts
  packages/core/src/router/specs/router.query.factory.spec.ts
Labels: bug

#149 feat(middleware-multipart): multipart/form-data middleware based on busboy library
  .gitignore
  packages/@integration/package.json
  packages/@integration/src/effects/static.effects.ts
  packages/core/src/server/specs/server.factory.spec.ts
  packages/middleware-body/src/body.middleware.ts
  packages/middleware-body/src/body.util.ts
  packages/middleware-io/src/io.request.middleware.ts
  packages/middleware-multipart/README.md
  packages/middleware-multipart/package.json
  packages/middleware-multipart/src/index.ts
  packages/middleware-multipart/src/multipart.interface.ts
  packages/middleware-multipart/src/multipart.middleware.ts
  packages/middleware-multipart/src/multipart.parser.field.ts
  packages/middleware-multipart/src/multipart.parser.file.ts
  packages/middleware-multipart/src/multipart.parser.ts
  packages/middleware-multipart/src/multipart.util.ts
  packages/middleware-multipart/src/specs/index.spec.ts
  packages/middleware-multipart/src/specs/multipart.middleware.spec.ts
  packages/middleware-multipart/src/specs/multipart.util.spec.ts
  packages/middleware-multipart/tsconfig.json
  yarn.lock
Labels: enhancement, scope: middleware

#150 Update README.md
  packages/serverless/README.md
Labels: docs

#151 fix(middleware-multipart): wait until whole stream is finished
  packages/middleware-multipart/src/multipart.parser.file.ts
  packages/middleware-multipart/src/multipart.parser.ts
Labels: bug, scope: middleware
